import Head from 'next/head'
const HeadComponent = () => {
  return ( 
    <div>
      <Head>
        <title>Dashboard Lama Dev</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
    </div>
   );
}
 
export default HeadComponent;