import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navbar/Navbar'
import Sidebar from '../components/sidebar/Sidebar'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>Dashboard Lama Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>
      </Head>
      <div className={styles.home}>
        <Sidebar />
        <div className={styles.home_container}>
          <Navbar />
          home container
        </div>
      </div>
      
      
    </div>
  )
}
